# Setup
title:               Peter Zhao
tagline:             'wistful thoughts'
description:         'Thoughts and musings'
url:                 https://pzhao1799.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Peter Zhao
  url:               https://pzhao1799.github.io
  email:             pzhao1799@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
