# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

encoding: UTF-8
# Site settings
title: Peter Zhao
email: pjz1@williams.edu
description: > # this means to ignore newlines until "baseurl:"
  Peter Zhao's website logging his personal thoughts, experiences, projects, and music
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://pzhao1799.github.io" # the base hostname & protocol for your site
github_username: pzhao1799
linkedin_username: peter-zhao

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes:  ["apos", "apos", "quot", "quot"]

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
